import os
from pathlib import Path

DEFAULT_SERVICE_NAME = 'DDS01'
DEFAULT_SERVICE_AUTO_START = True
DEFAULT_SERVICE_API_HOST = '127.0.0.1'
DEFAULT_SERVICE_API_PORT = 8085

DEFAULT_SERVICE_ROOT_PATH = 'C:\\Users\\spoof\\Desktop'
DEFAULT_SERVICE_STAGING_PATH = 'C:\\Users\\spoof\\Desktop'

DEFAULT_ORTHANC_URL = "http://192.168.1.50:8042"
DEFAULT_ORTHANC_USERNAME = "orthanc_user"
DEFAULT_ORTHANC_PASSWORD = "orthanc_pass"

SERVICE_NAME = 'DDS01'
SERVICE_AUTO_START = True
SERVICE_API_HOST = '127.0.0.1'
SERVICE_API_PORT = 8085

SERVICE_ROOT_PATH = 'C:\\Users\\spoof\\Desktop'
SERVICE_STAGING_PATH = 'C:\\Users\\spoof\\Desktop'

ORTHANC_URL = DEFAULT_ORTHANC_URL
ORTHANC_USERNAME = DEFAULT_ORTHANC_USERNAME
ORTHANC_PASSWORD = DEFAULT_ORTHANC_PASSWORD
